import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def train_model():
    data = {
        "subject": [
            "Resuelve tu Deuda",
            "Reunión programada para mañana",
            "Tu cuenta ha sido comprometida, haz clic aquí",
            "Oferta especial sólo para tí",
            "Actualización de política de privacidad",
            "Tu suscripción ha sido renovada",
            "Gana un viaje gratis",
            "Notificación de pago pendiente",
            "Verifica tu cuenta de seguridad",
            "Importante: Confirma tus datos personales",
            "¡Gana un premio increíble!",
            "Tu cuenta será desactivada si no haces clic aquí",
            "Promoción exclusiva por tiempo limitado",
            "Confirmación de reserva de vuelo",
            "Actualización de información de cuenta",
            "¡Felicidades! Eres nuestro ganador",
            "¡Tu factura está lista para su pago!",
            "Oferta especial solo por hoy",
            "Verificación de identidad requerida",
            "Confirma tu compra en línea",
            "Importante: Actualización de seguridad de la cuenta",
            "Tu contraseña ha sido restablecida",
            "Tu membresía expirará pronto",
            "Revise su actividad de inicio de sesión reciente",
            "Gana un iPhone gratis",
            "Descubre las últimas ofertas en electrónicos",
            "Actualización obligatoria de la cuenta",
            "Su cuenta ha sido bloqueada temporalmente",
            "Nuevo mensaje importante de seguridad",
            "Su acceso ha sido restringido",
            "Confirma tu dirección de correo electrónico",
            "Actualización de la política de cookies",
            "Recupera tu cuenta ahora",
            "Tu cuenta ha sido comprometida, por favor, restablece tu contraseña",
            "Oferta exclusiva para nuestros clientes VIP",
            "¡Tu membresía ha sido aprobada!",
            "Aviso de pago de factura pendiente",
            "Confirma tu reserva de hotel",
            "Atención: Actualización de términos y condiciones",
            "Tu cuenta está en riesgo",
            "¡Nuevo mensaje de voz recibido!",
            "Recordatorio de reunión",
            "Actualización importante de privacidad",
            "Comprueba tu cuenta de seguridad ahora",
            "Participa en nuestra encuesta y gana",
            "Su cuenta ha sido bloqueada",
            "Su cuenta se ha visto comprometida",
            "Verificación de la dirección de correo electrónico",
            "¡Felicidades! Eres un ganador de la lotería",
            "Gana un bono de $1000 ahora",
            "Revisa tu factura de pago",
            "Actualización requerida de la cuenta",
            "Confirma tu suscripción",
            "Atención: Información de cuenta incorrecta",
            "Tu cuenta ha sido suspendida temporalmente",
            "Necesitamos confirmar tu identidad",
            "¡Nuevo mensaje urgente!",
            "Oferta especial para nuevos suscriptores",
            "Renueva tu membresía ahora",
            "Actualización de la política de privacidad",
            "Importante: Acción requerida en tu cuenta",
            "Confirmación de pago",
            "Tu cuenta está en peligro",
            "Revisión de la actividad de la cuenta",
            "Gana un viaje de lujo",
            "Actualización de seguridad importante",
            "Tu compra ha sido procesada correctamente",
            "Verificación de la dirección de entrega",
            "Aviso de pago vencido",
            "¡Felicidades! Has ganado un premio en efectivo",
            "Confirma tu cuenta de correo electrónico ahora",
            "¡Tu crédito ha sido aprobado!",
            "Revisa tu transacción reciente",
            "Tu cuenta ha sido suspendida",
            "¡Nuevo mensaje importante!",
            "Verifica tu información personal",
            "Última oportunidad para reclamar tu premio",
            "Actualización de términos de servicio",
            "Tu suscripción ha sido cancelada",
            "Actualización requerida de la seguridad de la cuenta",
            "Recuerda confirmar tu dirección de correo electrónico",
            "¡Felicidades! Eres el ganador de nuestra promoción",
            "Recordatorio de renovación de membresía",
            "Acción requerida: Confirma tu dirección de correo electrónico",
            "Confirma tu identidad para evitar el bloqueo de la cuenta",
            "Oferta exclusiva para suscriptores",
            "Confirmación de compra en línea",
            "Atención: Tu cuenta está en riesgo",
            "Actualización importante sobre tu cuenta",
            "Verifica tu cuenta de seguridad de inmediato",
            "¡Gana un viaje todo incluido!",
            "¡Tu solicitud ha sido aprobada!",
            "Aviso de factura pendiente",
            "Confirma tu dirección de facturación",
            "Atención: Problemas con tu cuenta",
            "¡Tu suscripción ha sido renovada automáticamente!",
            "Actualización de seguridad crítica",
            "Tu pedido está en camino",
            "Revisa tu suscripción",
            "Confirma tu asistencia al evento",
            "Recupera el acceso a tu cuenta ahora",
            "Tu cuenta será desactivada temporalmente",
            "Última oportunidad para reclamar tu premio",
            "Verificación de la cuenta de correo electrónico",
            "¡Nueva notificación urgente!",
            "Gana un premio especial",
            "Actualización de la dirección de envío",
            "Tu suscripción expirará pronto",
            "Confirmación de reserva de hotel",
            "Atención: Problema con la facturación",
            "Revisa tu estado de cuenta",
            "¡Tu cuenta está en peligro! Confirma tus detalles ahora",
            "Tu compra ha sido procesada con éxito",
            "Verificación de cuenta necesaria",
            "Aviso de pago pendiente",
            "¡Felicidades! Has ganado una tarjeta de regalo",
            "Renueva tu membresía hoy",
            "Acción requerida: Verifica tu identidad ahora"
        ],
        "label": [
            "Phishing",
            "Legit",
            "Phishing",
            "Legit",
            "Legit",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Legit",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Legit",
            "Legit",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Phishing",
            "Legit",
            "Phishing"
        ]
    }
    df = pd.DataFrame(data)
    df['subject'] = df['subject'].str.lower()  # Convertir a minúsculas
    X = df["subject"]
    y = df["label"]
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = make_pipeline(
        TfidfVectorizer(min_df=1, stop_words=None, token_pattern=r'\b\w+\b'),
        MultinomialNB(alpha=1.0)  # Ajuste del parámetro alpha para MultinomialNB
    )
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f'Precisión del modelo en datos de prueba: {accuracy:.2f}')
    return model
